import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Navbar from "@/components/Navbar";
import Footer from '@/components/Footer';
import '@/styles/style.css';


export const metadata = {
  title: "TechnoVenture 3.0",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <>
        <Navbar />
        {children}
        <Footer />
    </>
  );
}
